controller_list:
  - name: Index_finger_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_0_0
      - joint_1_0
      - joint_2_0
      - joint_3_0
  - name: Middle_finger_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_4_0
      - joint_5_0
      - joint_6_0
      - joint_7_0
  - name: Ring_finger_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_8_0
      - joint_9_0
      - joint_10_0
      - joint_11_0
  - name: Thumb_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_12_0
      - joint_13_0
      - joint_14_0
      - joint_15_0
  - name: HAND_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_0_0
      - joint_1_0
      - joint_2_0
      - joint_3_0
      - joint_12_0
      - joint_13_0
      - joint_14_0
      - joint_15_0
      - joint_4_0
      - joint_5_0
      - joint_6_0
      - joint_7_0
      - joint_8_0
      - joint_9_0
      - joint_10_0
      - joint_11_0