Index_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_0_0
    - joint_1_0
    - joint_2_0
  gains:
    joint_0_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_1_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_2_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
Middle_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_3_0
    - joint_4_0
    - joint_5_0
  gains:
    joint_3_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_4_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_5_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
Thumb_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_6_0
    - joint_7_0
    - joint_8_0
  gains:
    joint_6_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_7_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_8_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
HAND_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_0_0
    - joint_1_0
    - joint_2_0
    - joint_3_0
    - joint_4_0
    - joint_5_0
    - joint_6_0
    - joint_7_0
    - joint_8_0
  gains:
    joint_0_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_1_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_2_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_4_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_5_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_6_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_7_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_8_0:
      p: 100
      d: 1
      i: 1
      i_clamp: 1